#include "fff.h"
#include "unity.h"

#include <openthread/platform/uart.h>

#include "user.h"

DEFINE_FFF_GLOBALS;

// This is #include Mockxyz, this was also autogenerated via CMOCK
// Creates a common struct
FAKE_VALUE_FUNC(otError, otPlatUartSend, const uint8_t *, uint16_t);

// setUp and tearDown HAVE to be declared
// If we didnt declare it used to go into the executable anyway
// Codegen
void setUp() {
  RESET_FAKE(otPlatUartSend);
  FFF_RESET_HISTORY();
}
void tearDown() {}

// What we wrote

void random_test_one(void) {
  // TEST_FAIL_MESSAGE("This Test has randomly failed");
  TEST_PASS_MESSAGE("This has to pass");
}

void user_send_hello_test() {
  user__send_hello();

  TEST_ASSERT_EQUAL_UINT16(otPlatUartSend_fake.call_count, 1);
}

void user_send_hello_test_again() {
  user__send_hello();

  TEST_ASSERT_EQUAL_UINT16(otPlatUartSend_fake.call_count, 1);
}

// Preet has made magic for us
// Codegen
int main() {
  UNITY_BEGIN();

  // Add my tests here
  RUN_TEST(random_test_one);
  RUN_TEST(user_send_hello_test);
  RUN_TEST(user_send_hello_test_again);

  return UNITY_END(); // Sends the error code and other debug stuff
}
